In [53]:
import pandas as pd
import numpy as np
import nltk
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [54]:
data = {
"CV_Text":[
"I am a creative designer who loves innovation and new ideas",
"I am a disciplined and organized person who completes work on time",
"I enjoy meeting people and public speaking",
"I always help others and work well in teams",
"I stay calm under pressure and manage stress easily"
],

"Personality":[
"Openness",
"Conscientiousness",
"Extraversion",
"Agreeableness",
"Emotional Stability"
]
}

df = pd.DataFrame(data)

df.head()

,CV_Text,Personality
0,I am a creative designer who loves innovation and new ideas,Openness
1,I am a disciplined and organized person who completes work on time,Conscientiousness
2,I enjoy meeting people and public speaking,Extraversion
3,I always help others and work well in teams,Agreeableness
4,I stay calm under pressure and manage stress easily,Emotional Stability

In [55]:
import pandas as pd
import re

# Pandas ko bolo ki text truncate na kare
pd.set_option('display.max_colwidth', None)

def clean_text(text):
    
    text = text.lower()                    # lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text) # special characters remove
    text = re.sub(r'\s+', ' ', text).strip() # extra spaces remove
    
    return text

df["cleaned_text"] = df["CV_Text"].apply(clean_text)

df

,CV_Text,Personality,cleaned_text
0,I am a creative designer who loves innovation and new ideas,Openness,i am a creative designer who loves innovation and new ideas
1,I am a disciplined and organized person who completes work on time,Conscientiousness,i am a disciplined and organized person who completes work on time
2,I enjoy meeting people and public speaking,Extraversion,i enjoy meeting people and public speaking
3,I always help others and work well in teams,Agreeableness,i always help others and work well in teams
4,I stay calm under pressure and manage stress easily,Emotional Stability,i stay calm under pressure and manage stress easily

In [56]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["cleaned_text"])

y = df["Personality"]

In [57]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [58]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [59]:
model = MultinomialNB()

model.fit(X, y)

prediction = model.predict(X)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y, prediction))

Accuracy: 1.0

In [60]:
def predict_personality(cv_text):

    cv_text = clean_text(cv_text)

    vector = vectorizer.transform([cv_text])

    prediction = model.predict(vector)

    return prediction[0]

In [61]:
cv = "I love teamwork and helping others in projects"

print("Predicted Personality:", predict_personality(cv))

Predicted Personality: Agreeableness